"""Add ML models and auditing

Revision ID: b0b7f2abf27b
Revises: 3279d83ae345
Create Date: 2026-07-11 18:27:45.410637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b0b7f2abf27b'
down_revision: Union[str, None] = '3279d83ae345'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alert_type', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('entity_id', sa.String(), nullable=True),
    sa.Column('is_resolved', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_alert_type'), 'alerts', ['alert_type'], unique=False)
    op.create_index(op.f('ix_alerts_id'), 'alerts', ['id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action_type'), 'audit_logs', ['action_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_table('dataset_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('file_hash', sa.String(), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('schema_info', sa.JSON(), nullable=True),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dataset_versions_id'), 'dataset_versions', ['id'], unique=False)
    op.create_index(op.f('ix_dataset_versions_name'), 'dataset_versions', ['name'], unique=False)
    op.create_table('ml_model_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=True),
    sa.Column('hyperparameters', sa.JSON(), nullable=True),
    sa.Column('artifact_path', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['dataset_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ml_model_versions_id'), 'ml_model_versions', ['id'], unique=False)
    op.create_index(op.f('ix_ml_model_versions_model_name'), 'ml_model_versions', ['model_name'], unique=False)
    op.create_table('prediction_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('prediction_type', sa.String(), nullable=True),
    sa.Column('input_data', sa.JSON(), nullable=True),
    sa.Column('prediction_result', sa.JSON(), nullable=True),
    sa.Column('explanation', sa.String(), nullable=True),
    sa.Column('predicted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['ml_model_versions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prediction_logs_id'), 'prediction_logs', ['id'], unique=False)
    op.create_index(op.f('ix_prediction_logs_prediction_type'), 'prediction_logs', ['prediction_type'], unique=False)
    op.drop_table('environmental_records_raw')
    op.drop_table('fitness_records_raw')
    op.drop_table('health_records_raw')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('health_records_raw',
    sa.Column('User_ID', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Age', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('Gender', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Height_cm', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('Weight_kg', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('Systolic_BP', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('Diastolic_BP', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('Fasting_Blood_Sugar', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('HbA1c', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('Smoking', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Alcohol', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Sleep_Hours', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('Exercise_Frequency', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Daily_Calories', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('Sugar_Intake_g', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('Family_History_Diabetes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('BMI', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('Diabetes_Risk', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False)
    )
    op.create_table('fitness_records_raw',
    sa.Column('Record_ID', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('User_ID', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Date', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Steps', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('Calories_Burned', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('Distance_km', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('Sleep_Hours', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('Resting_Heart_Rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('Active_Minutes', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('Floors_Climbed', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False)
    )
    op.create_table('environmental_records_raw',
    sa.Column('Record_ID', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('City', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Date', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('AQI', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('PM2_5', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('PM10', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('Humidity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('Temperature_C', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('NO2', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('SO2', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False)
    )
    op.drop_index(op.f('ix_prediction_logs_prediction_type'), table_name='prediction_logs')
    op.drop_index(op.f('ix_prediction_logs_id'), table_name='prediction_logs')
    op.drop_table('prediction_logs')
    op.drop_index(op.f('ix_ml_model_versions_model_name'), table_name='ml_model_versions')
    op.drop_index(op.f('ix_ml_model_versions_id'), table_name='ml_model_versions')
    op.drop_table('ml_model_versions')
    op.drop_index(op.f('ix_dataset_versions_name'), table_name='dataset_versions')
    op.drop_index(op.f('ix_dataset_versions_id'), table_name='dataset_versions')
    op.drop_table('dataset_versions')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action_type'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_alerts_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_alert_type'), table_name='alerts')
    op.drop_table('alerts')
    # ### end Alembic commands ###
